### Submit Leave Request (POST)
POST http://localhost:3000/leave-requests
Content-Type: application/json

{
  "employeeId": "03a73b82-fc3c-4afc-a5c0-9b32cfabddf6",
  "type": "Vacation",
  "startDate": "2025-09-10",
  "endDate": "2025-09-16",
  "reason": "Family holiday and travel."
}

### Get All Leave Requests (GET)
GET http://localhost:3000/leave-requests

### Approve a Leave Request (PUT)
PUT http://localhost:3000/leave-requests/858c412a-ef7b-48ea-a132-a6200835fce8/status
Content-Type: application/json

{
    "status": "Approved"
}

### Reject a Leave Request (PUT)
PUT http://localhost:3000/leave-requests/858c412a-ef7b-48ea-a132-a6200835fce8/status
Content-Type: application/json

{
    "status": "Rejected"
}